spring:
  cloud:
    name:
      CONFIG
    config:
      server:
        native:
#          search-locations: classpath:/config
          search-locations: ./config
#          search-locations: file:/D:\immerex\immerex\configserver\src\main\resources\config
#  rabbitmq:
#    host: 192.168.0.232
#    port: 5672
#    password: test
#    username: test
#    virtual-host: test
#    requested-heartbeat: 5
#    listener:
#      concurrency: 2
#      max-concurrency: 5
#      acknowledge-mode: manual

#logging:
#  level:
#    com.netflix.discovery: 'OFF'
#    org.springframework.cloud: 'DEBUG'