discovery:
  image: discovery:latest
  ports:
    - 8761:8761
  volumes:
    - /temp:/temp
  environment:
    - JAVA_OPTS="-Xms5000m -Xmx10000m"
  command: bash -c "java -jar /discovery.jar"
configserver:
  image: configserver:latest
  ports:
   - 8888:8888
  volumes:
   - /temp:/temp
  environment:
   - JAVA_OPTS="-Xms5000m -Xmx10000m"
  command: bash -c "java -jar /configserver.jar"
  links:
  - discovery