#RabbitMQ property set
spring:
  redis:
    database: 0
    host: server-redis.a88y7c.ng.0001.apne1.cache.amazonaws.com
    port: 6379
    password:
    max-total: 5
    max-idle: 2
    min-idle: 2
    max-active: 5
    max-wait: -1
    max-wait-millis: 1000
    test-on-borrow: true
    test-on-return: true
  custom:
    test: a
sessionVr:
  duration: 12 #表示小时数
tokenVr:
  duration:  168 #7*24表示天数