spring:
  rabbitmq:
    host: 192.168.0.232
    port: 5672
    password: test
    username: test
    virtual-host: test
    requested-heartbeat: 5
    listener:
#      concurrency: 2
#      max-concurrency: 5
#      acknowledge-mode: manual
  c3p0:
    driverClass: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.0.233:3306/vr_log?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    user: root
    password: 123456789
    acquireIncrement: 1
    initialPoolSize: 2
    maxIdleTime: 2
    maxPoolSize: 2
    minPoolSize: 2
    acquireRetryDelay: 1000
    acquireRetryAttempts: 60
    minPoolSizebreakAfterAcquireFailure: false
  redis:
    cluster:
      nodes:
        - 192.168.0.232:7000
        - 192.168.0.232:7001
        - 192.168.0.232:7002
        - 192.168.0.232:7003
        - 192.168.0.232:7004
        - 192.168.0.232:7005
      max-redirects: 10
      timeout: 5000
      max-total: 300
      max-idle: 20
      max-wait-millis: 1000
      test-on-borrow: true
      test-on-return: true
#      db-index: 1
  custom:
    test: a
#server:
#  context-path: /spring-some

