spring:
  rabbitmq:
    host: ec2-52-199-106-99.ap-northeast-1.compute.amazonaws.com
    port: 5672
    password: test
    username: test
    virtual-host: test
    requested-heartbeat: 5
    listener:
#      concurrency: 2
#      max-concurrency: 5
#      acknowledge-mode: manual
  c3p0:
    driverClass: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://awstest.cebx4ele6g6j.ap-northeast-1.rds.amazonaws.com:3306/vr_log?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    user: awstest
    password: 123456789
    acquireIncrement: 1
    initialPoolSize: 2
    maxIdleTime: 2
    maxPoolSize: 2
    minPoolSize: 2
    acquireRetryDelay: 1000
    acquireRetryAttempts: 60
    minPoolSizebreakAfterAcquireFailure: false
  redis:
    cluster:
      nodes:
        - redis-test-0001-001.a88y7c.0001.apne1.cache.amazonaws.com:6379
        - redis-test-0001-002.a88y7c.0001.apne1.cache.amazonaws.com:6379
        - redis-test-0002-001.a88y7c.0001.apne1.cache.amazonaws.com:6379
        - redis-test-0002-002.a88y7c.0001.apne1.cache.amazonaws.com:6379
        - redis-test-0003-001.a88y7c.0001.apne1.cache.amazonaws.com:6379
        - redis-test-0003-002.a88y7c.0001.apne1.cache.amazonaws.com:6379
      max-redirects: 10
      timeout: 5000
      max-total: 300
      max-idle: 20
      max-wait-millis: 1000
      test-on-borrow: true
      test-on-return: true
#      db-index: 1
  custom:
    test: a
#server:
#  context-path: /spring-some

