spring:
  rabbitmq:
    host: 192.168.0.108
    port: 5672
    password: zhangjiming
    username: zhangjiming
    virtual-host: zhangjiming
    requested-heartbeat: 5
    listener:
#      concurrency: 2
#      max-concurrency: 5
#      acknowledge-mode: manual
  c3p0:
    driverClass: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.0.108:3306/module1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    user: root
    password: 123456789
    acquireIncrement: 1
    initialPoolSize: 2
    maxIdleTime: 2
    maxPoolSize: 2
    minPoolSize: 2
    acquireRetryDelay: 1000
    acquireRetryAttempts: 60
    minPoolSizebreakAfterAcquireFailure: false
  redis:
    cluster:
      nodes:
        - 192.168.0.108:7000
        - 192.168.0.108:7001
        - 192.168.0.108:7002
        - 192.168.0.108:7003
        - 192.168.0.108:7004
        - 192.168.0.108:7005
      max-redirects: 10
      timeout: 5000
      max-total: 300
      max-idle: 20
      max-wait-millis: 1000
      test-on-borrow: true
      test-on-return: true
#      db-index: 1
  custom:
    test: b

feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
#  histrix:
#    enabled: false

#hystrix:
#  command:
#    choose:
#      default:
#        execution:
#          timeout:
#            enabled: false

hystrix:
  command:
    default:
      execution:
#        timeout:
#          enabled: false   #禁用超时
        isolation:
          thread:
            timeoutInMilliseconds: 50000  #默认feign超时时间,如果要单独针对某方法设置的话把default改成对应的方法名即可


#server:
#  context-path: /spring-some

aws:
  credentials:
    accessKey: AKIAIC2LLSVASGSXMTIQ
    secretAccessKey: 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
  s3:
    region: us-west-1
    web_commerce_static_bucket_name: web-commerce-static-536df403-fbd5-45ab-8ab3-551a5997cb6e
    web_store_static_bucket_name: web-store-static-536df403-fbd5-45ab-8ab3-551a5997cb6e
    store_app_bucket_name: store-app-file-536df403-fbd5-45ab-8ab3-551a5997cb6e
    store_content_bucket_name: store-content-file-536df403-fbd5-45ab-8ab3-551a5997cb6e
  cdn:
    storeAppDistributionDomain: http://d16ibtie31j82f.cloudfront.net
    storeContentDistributionDomain: http://d3lx6xyw1zwr0r.cloudfront.net
    keyPairId: APKAJDTCREWHG27ILCPQ
    privateKeyFilePath: /Users/zhangjiming/amazon/huangzhen/aws-cloudfront-pk.der