spring:
#  rabbitmq:
#    host: 192.168.0.108
#    port: 5672
#    password: zhouhe
#    username: zhouhe
#    virtual-host: zhouhe
#    requested-heartbeat: 5
#    listener:
#      concurrency: 2
#      max-concurrency: 5
#      acknowledge-mode: manual
  c3p0:
    driverClass: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://immerex.cebx4ele6g6j.ap-northeast-1.rds.amazonaws.com:3306/module1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    user: immerex
    password: 123456789
    acquireIncrement: 1
    initialPoolSize: 2
    maxIdleTime: 2
    maxPoolSize: 2
    minPoolSize: 2
    acquireRetryDelay: 1000
    acquireRetryAttempts: 60
    minPoolSizebreakAfterAcquireFailure: false
#  redis:
#    cluster:
#      nodes:
#        - 192.168.0.108:7000
#        - 192.168.0.108:7001
#        - 192.168.0.108:7002
#        - 192.168.0.108:7003
#        - 192.168.0.108:7004
#        - 192.168.0.108:7005
#      max-redirects: 10
#      timeout: 5000
#      max-total: 300
#      max-idle: 20
#      max-wait-millis: 1000
#      test-on-borrow: true
#      test-on-return: true
##      db-index: 1
  redis:
    database: 0
    host: 192.168.0.108
    port: 6379
    password:
    max-total: 5
    max-idle: 2
    min-idle: 2
    max-active: 5
    max-wait: -1
    max-wait-millis: 1000
    test-on-borrow: true
    test-on-return: true
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
#  histrix:
#    enabled: false

#hystrix:
#  command:
#    choose:
#      default:
#        execution:
#          timeout:
#            enabled: false

hystrix:
  command:
    default:
      execution:
#        timeout:
#          enabled: false   #禁用超时
        isolation:
          thread:
            timeoutInMilliseconds: 50000  #默认feign超时时间,如果要单独针对某方法设置的话把default改成对应的方法名即可


#server:
#  context-path: /spring-some

