spring:
#  rabbitmq:
#    host: 192.168.0.108
#    port: 5672
#    password: hechaozhen
#    username: hechaozhen
#    virtual-host: hechaozhen
#    requested-heartbeat: 5
#    listener:
#      concurrency: 2
#      max-concurrency: 5
#      acknowledge-mode: manual
  mail:
    host: smtp.qiye.163.com
    username: zhouhe@kokozu.net
    password: 12!@#$Ab
  properties:
    mail:
      smtp:
       auth: true
  c3p0:
    driverClass: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.11.126:3306/immerex_user_center?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    user: root
    password: 123456789
    acquireIncrement: 1
    initialPoolSize: 2
    maxIdleTime: 2
    maxPoolSize: 2
    minPoolSize: 2
    acquireRetryDelay: 1000
    acquireRetryAttempts: 60
    minPoolSizebreakAfterAcquireFailure: false
#  redis:
#    cluster:
#      nodes:
#        - 192.168.0.108:7000
#        - 192.168.0.108:7001
#        - 192.168.0.108:7002
#        - 192.168.0.108:7003
#        - 192.168.0.108:7004
#        - 192.168.0.108:7005
#      max-redirects: 10
#      timeout: 5000
#      max-total: 300
#      max-idle: 20
#      max-wait-millis: 1000
#      test-on-borrow: true
#      test-on-return: true
##      db-index: 1
  redis:
    database: 0
    host: 192.168.11.126
    port: 6379
    password:
    max-total: 5
    max-idle: 2
    min-idle: 2
    max-active: 5
    max-wait: -1
    max-wait-millis: 1000
    test-on-borrow: true
    test-on-return: true
  custom:
    test: a
encrypt:
  globalKey: 661ee319dff061d4fb6532787f7b6927
  passSalt: w1fsd2DurO0
keyencode:
  DESede: 68EC34C420E6CDA1511A2A40CE94897FA2089EAD6E15D62C

###消息推送###
push:
#Demo
#  host: http://sdk.open.api.igexin.com/apiex.htm
#  appId: Y6WTlm6n56A2XlUVQ3TFu9
#  appKey: 7sczG1wj226Zpq3SL9Kzq7
#  masterSecret: 8JYiusQT1a5fSaqEHftEg2

# Phone App Test Env
  host: http://sdk.open.api.igexin.com/apiex.htm
  appId: ryJ6mSbQVT7uoCtmfgCGa4
  appKey: qFMBlrBAXSA97rpe9unUH7
  masterSecret: 5fMuzYnx6AATIitRBhgtbA
