my:
  message: some from docker
  
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: test
    username: test
    virtual-host: test
    requested-heartbeat: 5

#server:
#  context-path: /spring-some
  